### ISSUE TITLE
"Export Layer Group" to aid in GIF creation

### ISSUE THREAD

**Issue by naturally-intelligent** [kamilburda/gimp-export-layers#52]
Hello!  I really love your plugin and use it a lot!  Thank you!!  :)

Lately I've come across a similar problem.  I'll have an image made of many layers, and I want to export the whole image, but with different layers activated, one-at-a-time, to create PNG frames.  Then, I'll make a GIF using "convert" on the command line.  

So what I do is put all the changing components into one layer group, then, one at a time, make each layer in the group visible, then export.  It combines all the other visible layers and makes an animation.  However this becomes excruciatingly slow once the GIF has 10+ frames, and if a mistake/change needs to be made, repeating the process is a headache!  This could definitely be automated.  I started wondering if I should try it myself...

So perhaps one solution could be to somehow select a Layer Group within Export Layers, and have an option in your plugin like "Export Layer Group Merged with Visible Layers".

**Comment by khalim19** [comment]
If I understand correctly, I believe you can already do this in 3.0 RC2:
* Open up the Export Layers dialog, go to Settings -> Show More Settings
* In the preview pane to the right, select all layers to be inserted as background and tag them as Background (right click on the selection and select Background)
* Do the same for layers meant to be in the foreground, using the Foreground tag
* Add operations "Insert background layers" and "Insert foreground layers"
* Add constraint "Only layers without tags" so that the back- and foreground layers are not exported

This should export individual layers with the same background and foreground.

You can check the image preview below the list of layers to see if the layer is going to be exported as desired. If you want to use the dimensions of the image canvas (rather than each layer), check "Use image size".

**Comment by naturally-intelligent** [comment]
Interesting!  Thanks for the response and instructions.  I will try this and let you know how it works out!

**Comment by naturally-intelligent** [comment]
Closing
