### ISSUE TITLE
Plugin Not Showing Up

### ISSUE THREAD

**Issue by rufking** [kamilburda/gimp-export-layers#56]
Export Layers shows up in GIMP 2.8, running python 2.7.2.
Then I installed GIMP 2.10, export layers didn't show and the python functionality wasn't working (python-fu console didn't open)
Changed to samj's portable 2.10, and python functionality returned but export layers still didn't show up on the file menu, plugin explorer etc. I know the files ('export_layers.py' and folder 'export_layers') are in the correct directory, python is operational and I am running the latest version:
What is the problem???

Version of Export Layers: 3.1

Version of GIMP:  both regular 2.10 and samj 2.10

Operating system: Windows 10, 64 bit

**Comment by khalim19** [comment]
I found out you can make the plug-in work by moving the `export_layers` folder to `[GIMP installation folder]\lib\python2.7\site-packages`. This works for both the regular and the portable version.

For some reason, the Windows installer for 2.10 on the official GIMP page was modified not long ago, relocating the path to Python within GIMP.

The reason why the plug-in no longer works is because the `export_layers.py` file assumes that `export_layers` subdirectory is are the same directory. This may be the reason why also the Python-Fu console does not show up.

Regardless, I am going to fix this for the next release, but in the meantime, you can use the workaround mentioned above.

**Comment by Ruf-K** [comment]
Great, thanks for the help!
It's working fine now.

**Comment by WilsonBradley** [comment]
In Windows 8.1 , I'm not even able to find the export_layers folder to do this work around.
Filter effects to not apply after it shows modifying progress.

**Comment by khalim19** [comment]
@WilsonBradley What version of Export Layers are you using?

What directory was the plug-in installed in? Is it one of the listed directories in the GIMP menu "Edit → Preferences → Folders → Plug-Ins"? If so, check the log files in the directory - `error.log` or `export_layers_error.log`. If they are not empty, paste their contents here so I could pin down the problem (hopefully).

**Comment by jtthewoodworker** [comment]
I could only get it to run if I disabled my virus scanner. I use Comodo.

**Comment by kamilburda** [comment]
Closing this due to the issue being stale.
