### ISSUE TITLE
When exporting layers with dots in their names, last part of layer name is missing from proposed file name

### ISSUE THREAD

**Issue by olegvm** [kamilburda/gimp-export-layers#93]
#### What went wrong?

When exporting layers, proposed file names are truncated when there are dots in layer names.

#### Steps to reproduce the problem
1. Layers in my image haves dates in their names, which results in multiple dots in layer name. E.g.:
- Layer 1 - "2020.12.02 - Text A"
- Layer 2 - "2020.12.12 - Text B"
2. When using "Export Layers" plugin, preview file names are missing the part after the last dot in layer name. I.e. "2020.12.02 - Text A" becomes "2020.12".

![issue](https://user-images.githubusercontent.com/16876280/104091457-27b1ef80-5286-11eb-952d-72a99a29c02c.png)

#### Configuration

Version of Export Layers: 3.3.1

Version of GIMP: 2.10.22

Operating system: Windows 10 Pro x64 (build 20H2)

**Comment by khalim19** [comment]
This is intentional - by default, everything after the last `.` is removed, in case the layer name contains a file extension.

You can adjust this behavior as follows:
1. Go to Settings -> Show More Settings.
2. In the text field next to "Save as:", type `[layer name, %e]`. This should preserve the entire layer name as you intended.

The screenshot shows this.
![image](https://user-images.githubusercontent.com/8005908/190856511-b9330a7b-8df2-4e2f-ae04-b55029216154.png)

**Comment by kamilburda** [comment]
Closing this as this was resolved.
